"""Verification check final

Revision ID: ade0afc09526
Revises: 969a978aa9ab
Create Date: 2025-11-08 01:47:32.672713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ade0afc09526'
down_revision: Union[str, Sequence[str], None] = '969a978aa9ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_org_owner_id'), table_name='organization')
    op.drop_constraint(op.f('organization_owner_id_fkey'), 'organization', type_='foreignkey')
    op.create_foreign_key(None, 'organization', 'users', ['owner_id'], ['id'])
    op.drop_index(op.f('idx_org_members_org_id'), table_name='organization_members')
    op.drop_constraint(op.f('organization_members_organization_id_fkey'), 'organization_members', type_='foreignkey')
    op.drop_constraint(op.f('organization_members_user_id_fkey'), 'organization_members', type_='foreignkey')
    op.create_foreign_key(None, 'organization_members', 'organization', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'organization_members', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('idx_team_org_id'), table_name='team')
    op.drop_constraint(op.f('team_organization_id_fkey'), 'team', type_='foreignkey')
    op.create_foreign_key(None, 'team', 'organization', ['organization_id'], ['id'])
    op.drop_index(op.f('idx_team_members_team_id'), table_name='team_members')
    op.drop_constraint(op.f('team_members_team_id_fkey'), 'team_members', type_='foreignkey')
    op.drop_constraint(op.f('team_members_user_id_fkey'), 'team_members', type_='foreignkey')
    op.create_foreign_key(None, 'team_members', 'team', ['team_id'], ['id'])
    op.create_foreign_key(None, 'team_members', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team_members', type_='foreignkey')
    op.drop_constraint(None, 'team_members', type_='foreignkey')
    op.create_foreign_key(op.f('team_members_user_id_fkey'), 'team_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('team_members_team_id_fkey'), 'team_members', 'team', ['team_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.drop_constraint(None, 'team', type_='foreignkey')
    op.create_foreign_key(op.f('team_organization_id_fkey'), 'team', 'organization', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_team_org_id'), 'team', ['organization_id'], unique=False)
    op.drop_constraint(None, 'organization_members', type_='foreignkey')
    op.drop_constraint(None, 'organization_members', type_='foreignkey')
    op.create_foreign_key(op.f('organization_members_user_id_fkey'), 'organization_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('organization_members_organization_id_fkey'), 'organization_members', 'organization', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_org_members_org_id'), 'organization_members', ['organization_id'], unique=False)
    op.drop_constraint(None, 'organization', type_='foreignkey')
    op.create_foreign_key(op.f('organization_owner_id_fkey'), 'organization', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_org_owner_id'), 'organization', ['owner_id'], unique=False)
    # ### end Alembic commands ###
